steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fair-grade-app',
    '--build-arg', 'DB_INSTANCE_CONNECTION_NAME=$DB_INSTANCE_CONNECTION_NAME',
    '--build-arg', 'DB_USER=$DB_USER',
    '--build-arg', 'DB_PASSWORD=$DB_PASSWORD',
    '--build-arg', 'DB_NAME=$DB_NAME',
    '--build-arg', 'AUTH_SECRET=$AUTH_SECRET',
    '--build-arg', 'AUTH_TRUST_HOST=$AUTH_TRUST_HOST',
    '--build-arg', 'AUTH_GITHUB_ID=$AUTH_GITHUB_ID',
    '--build-arg', 'AUTH_GITHUB_SECRET=$AUTH_GITHUB_SECRET',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fair-grade-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fair-grade-app', '--image', 'gcr.io/$PROJECT_ID/fair-grade-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/fair-grade-app'
logsBucket: gs://744541105758-global-cloudbuild-logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
 