steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fair-grade-app',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/$PROJECT_ID/fair-grade-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'fair-grade-app', 
    '--image', 'gcr.io/$PROJECT_ID/fair-grade-app', 
    '--region', 'us-central1', 
    '--platform', 'managed', 
    '--allow-unauthenticated'
  ]

images:
- 'gcr.io/$PROJECT_ID/fair-grade-app'

logsBucket: gs://744541105758-global-cloudbuild-logs

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET