steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fair-grade-app',
    '--build-arg', 'AUTH_SECRET=$_AUTH_SECRET',
    '--build-arg', 'AUTH_TRUST_HOST=$_AUTH_TRUST_HOST',
    '--build-arg', 'AUTH_GITHUB_ID=$_AUTH_GITHUB_ID',
    '--build-arg', 'AUTH_GITHUB_SECRET=$_AUTH_GITHUB_SECRET',
    '--build-arg', 'AUTH_GOOGLE_ID=$_AUTH_GOOGLE_ID',
    '--build-arg', 'AUTH_GOOGLE_SECRET=$_AUTH_GOOGLE_SECRET',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fair-grade-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fair-grade-app', '--image', 'gcr.io/$PROJECT_ID/fair-grade-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/fair-grade-app'
logsBucket: gs://744541105758-global-cloudbuild-logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
 