substitutions:
  _DATABASE_URL: "projects/symmetric-ray-425503-d6/secrets/DATABASE_URL/versions/latest"
  _GOOGLE_APPLICATION_CREDENTIALS: "projects/symmetric-ray-425503-d6/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/latest"
  _AUTH_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_SECRET/versions/latest"
  _AUTH_GITHUB_ID: "projects/symmetric-ray-425503-d6/secrets/AUTH_GITHUB_ID/versions/latest"
  _AUTH_GITHUB_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_GITHUB_SECRET/versions/latest"
  _AUTH_GOOGLE_ID: "projects/symmetric-ray-425503-d6/secrets/AUTH_GOOGLE_ID/versions/latest"
  _AUTH_GOOGLE_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_GOOGLE_SECRET/versions/latest"

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Fetch secrets from Secret Manager'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      DATABASE_URL=$(gcloud secrets versions access latest --secret="${_DATABASE_URL}")
      GOOGLE_APPLICATION_CREDENTIALS=$(gcloud secrets versions access latest --secret="${_GOOGLE_APPLICATION_CREDENTIALS}")
      AUTH_SECRET=$(gcloud secrets versions access latest --secret="${_AUTH_SECRET}")
      AUTH_GITHUB_ID=$(gcloud secrets versions access latest --secret="${_AUTH_GITHUB_ID}")
      AUTH_GITHUB_SECRET=$(gcloud secrets versions access latest --secret="${_AUTH_GITHUB_SECRET}")
      AUTH_GOOGLE_ID=$(gcloud secrets versions access latest --secret="${_AUTH_GOOGLE_ID}")
      AUTH_GOOGLE_SECRET=$(gcloud secrets versions access latest --secret="${_AUTH_GOOGLE_SECRET}")

      # Create .env.production file with fetched secrets
      echo "DATABASE_URL=$DATABASE_URL" > .env.production
      echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> .env.production
      echo "AUTH_SECRET=$AUTH_SECRET" >> .env.production
      echo "AUTH_TRUST_HOST=https://fair-grade-app-vpz4vvqzlq-uc.a.run.app" >> .env.production
      echo "NEXTAUTH_URL=https://fair-grade-app-vpz4vvqzlq-uc.a.run.app" >> .env.production
      echo "AUTH_GITHUB_ID=$AUTH_GITHUB_ID" >> .env.production
      echo "AUTH_GITHUB_SECRET=$AUTH_GITHUB_SECRET" >> .env.production
      echo "AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID" >> .env.production
      echo "AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET" >> .env.production

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fair-grade-app',
    '--build-arg', 'ENV_FILE=.env.production',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/$PROJECT_ID/fair-grade-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fair-grade-app', '--image', 'gcr.io/$PROJECT_ID/fair-grade-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
- 'gcr.io/$PROJECT_ID/fair-grade-app'

logsBucket: gs://744541105758-global-cloudbuild-logs

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
