steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fair-grade-app',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args: ['push', 'gcr.io/$PROJECT_ID/fair-grade-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fair-grade-app', '--image', 'gcr.io/$PROJECT_ID/fair-grade-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated',
   '--update-env-vars', 'DATABASE_URL=${_DATABASE_URL},GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS},AUTH_SECRET=${_AUTH_SECRET},AUTH_TRUST_HOST=${_AUTH_TRUST_HOST},NEXTAUTH_URL=${_NEXTAUTH_URL},AUTH_GITHUB_ID=${_AUTH_GITHUB_ID},AUTH_GITHUB_SECRET=${_AUTH_GITHUB_SECRET},AUTH_GOOGLE_ID=${_AUTH_GOOGLE_ID},AUTH_GOOGLE_SECRET=${_AUTH_GOOGLE_SECRET}'
  ]

images:
- 'gcr.io/$PROJECT_ID/fair-grade-app'

logsBucket: gs://744541105758-global-cloudbuild-logs

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _DATABASE_URL: "projects/symmetric-ray-425503-d6/secrets/DATABASE_URL:latest"
  _GOOGLE_APPLICATION_CREDENTIALS: "projects/symmetric-ray-425503-d6/secrets/GOOGLE_APPLICATION_CREDENTIALS:latest"
  _AUTH_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_SECRET:latest"
  _AUTH_TRUST_HOST: "projects/symmetric-ray-425503-d6/secrets/AUTH_TRUST_HOST:latest"
  _NEXTAUTH_URL: "projects/symmetric-ray-425503-d6/secrets/NEXTAUTH_URL:latest"
  _AUTH_GITHUB_ID: "projects/symmetric-ray-425503-d6/secrets/AUTH_GITHUB_ID:latest"
  _AUTH_GITHUB_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_GITHUB_SECRET:latest"
  _AUTH_GOOGLE_ID: "projects/symmetric-ray-425503-d6/secrets/AUTH_GOOGLE_ID:latest"
  _AUTH_GOOGLE_SECRET: "projects/symmetric-ray-425503-d6/secrets/AUTH_GOOGLE_SECRET:latest"
