version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        DB_INSTANCE_CONNECTION_NAME: ${DB_INSTANCE_CONNECTION_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
        AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_INSTANCE_CONNECTION_NAME: ${DB_INSTANCE_CONNECTION_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/symmetric-ray-425503-d6-b10d3a717eaf.json
    volumes:
      - ./symmetric-ray-425503-d6-b10d3a717eaf.json:/secrets/symmetric-ray-425503-d6-b10d3a717eaf.json
