version: '3.8'

services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
        AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
        AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
        AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}

